services:
  mysql:
    image: mysql
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mysql-cli:
    image: mysql
    container_name: mysql_cli
    command: >
      bash -c "
      while ! mysqladmin ping -h 'mysql' --silent; do
        sleep 1
      done;
      mysql -h mysql -u root -proot_password airlines"
    depends_on:
      - mysql
    stdin_open: true
    tty: true

volumes:
  mysql_data:
